
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

ticketing:
    resource: "@TicketingBundle/Controller/"
    type:     annotation
    prefix:   /



fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

